apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance:  {{ .Values.zookeeper.name }}
    app.kubernetes.io/name: zookeeper
    strimzi.io/kind: zookeeper
  name:  {{ .Values.zookeeper.name }}
  namespace:  {{ .Release.Namespace }}