---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: zookeeper
    strimzi.io/kind: zookeeper
  name: {{ .Values.zookeeper.name }}-client
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: tcp-clients
    port: 2181
    protocol: TCP
    targetPort: 2181
  selector:
    strimzi.io/kind: zookeeper
    app.kubernetes.io/name: zookeeper
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: zookeeper
    strimzi.io/kind: zookeeper
  name: {{ .Values.zookeeper.name }}-nodes
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: tcp-clients
    port: 2181
    protocol: TCP
    targetPort: 2181
  - name: tcp-clustering
    port: 2888
    protocol: TCP
    targetPort: 2888
  - name: tcp-election
    port: 3888
    protocol: TCP
    targetPort: 3888
  publishNotReadyAddresses: true
  selector:
    strimzi.io/kind: zookeeper
    app.kubernetes.io/name: zookeeper
  sessionAffinity: None
  type: ClusterIP