FROM qiffang199133/kafka:0.25.0-kafka-2.8.0

USER root

COPY zookeeper_config_generator.sh /opt/kafka/zookeeper_config_generator.sh
COPY zookeeper_healthcheck.sh /opt/kafka/zookeeper_healthcheck.sh
COPY zookeeper_run.sh /opt/kafka/zookeeper_run.sh
COPY kafka_run.sh /opt/kafka/kafka_run.sh
