# Default values for kafka.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

zookeeper:
  image: qiffang199133/kafka:0.25.0-kafka-2.8.0-dev.12
  name: my-cluster-zookeeper
  replicas: 3

kafka:
  name: my-cluster-kafka
  replicas: 3
  image: qiffang199133/kafka:0.25.0-kafka-2.8.0-dev.12
  version: 2.8
